name: web_utils
description: A collection of useful Dart extensions for web development, enhancing JavaScript interop and simplifying common operations with the `web` package.
version: 1.0.18
repository: https://github.com/gmpassos/web_utils

environment:
  sdk: ^3.6.0

dependencies:
  js_interop_utils: ^1.0.9
  web: ^1.1.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.28.0
  dependency_validator: ^5.0.3

#dependency_overrides:
#  js_interop_utils:
#    path: ../js_interop_utils
